/*
 * Runs inside the target PHP docker image (which ships Zend headers) and
 * prints a struct-offset header for that exact PHP build. The tracer never
 * hardcodes zend layout: everything version-dependent flows through here.
 *
 *   gcc $(php-config --includes) -o gen_offsets gen_offsets.c
 *   ./gen_offsets php83 > offsets_php83.h
 */
#define _GNU_SOURCE /* Zend headers use memrchr */
#include <stdio.h>
#include <stddef.h>

#include <main/php.h>
#include <main/SAPI.h>
#include <Zend/zend_globals.h>
#include <Zend/zend_compile.h>
#include <ext/mysqlnd/mysqlnd.h>
#include <ext/mysqlnd/mysqlnd_structs.h>

int main(int argc, char **argv)
{
    const char *tag = argc > 1 ? argv[1] : "php";
    printf("/* generated by gen_offsets.c for PHP %s — do not edit */\n", PHP_VERSION);
    printf("#define %s_OFFSETS_INIT { \\\n", tag);
    printf("  .eg_current_execute_data = %zu, \\\n",
           offsetof(zend_executor_globals, current_execute_data));
    printf("  .ed_func                 = %zu, \\\n", offsetof(zend_execute_data, func));
    printf("  .ed_prev                 = %zu, \\\n", offsetof(zend_execute_data, prev_execute_data));
    printf("  .func_type               = %zu, \\\n", offsetof(zend_function, type));
    printf("  .func_name               = %zu, \\\n", offsetof(zend_function, common.function_name));
    printf("  .func_scope              = %zu, \\\n", offsetof(zend_function, common.scope));
    printf("  .oparr_filename          = %zu, \\\n", offsetof(zend_op_array, filename));
    printf("  .zstr_len                = %zu, \\\n", offsetof(zend_string, len));
    printf("  .zstr_val                = %zu, \\\n", offsetof(zend_string, val));
    printf("  .ce_name                 = %zu, \\\n", offsetof(zend_class_entry, name));
    printf("  .sg_request_method       = %zu, \\\n",
           offsetof(sapi_globals_struct, request_info.request_method));
    printf("  .sg_request_uri          = %zu, \\\n",
           offsetof(sapi_globals_struct, request_info.request_uri));
    printf("  .mysqlnd_m_query         = %zu, \\\n",
           offsetof(struct st_mysqlnd_conn_data_methods, query));
    printf("}\n");
    return 0;
}
