/* Shared between phptrace.bpf.c (kernel) and main.c (userspace). */
#ifndef PHPTRACE_H
#define PHPTRACE_H

#define MAX_FRAMES 48
#define MAX_URI    128
#define MAX_METHOD 8
#define MAX_QUERY  256

/* Version-dependent zend struct offsets, generated by gen_offsets.c.
 * Lives in the per-pid config map so one tracer instance can handle
 * multiple PHP builds (8.3 fpm + 7.4 mod_php) at once. */
struct php_offsets {
    unsigned int eg_current_execute_data;
    unsigned int ed_func;
    unsigned int ed_prev;
    unsigned int func_type;
    unsigned int func_name;
    unsigned int func_scope;
    unsigned int oparr_filename;
    unsigned int zstr_len;
    unsigned int zstr_val;
    unsigned int ce_name;
    unsigned int sg_request_method;
    unsigned int sg_request_uri;
    unsigned int mysqlnd_m_query;
};

/* Per-pid runtime config: resolved global addresses + offsets. */
struct proc_cfg {
    unsigned long long eg_addr;   /* &executor_globals in target */
    unsigned long long sg_addr;   /* &sapi_globals in target (0 if n/a) */
    struct php_offsets off;
};

enum ev_type {
    EV_SAMPLE    = 1,
    EV_REQ_START = 2,
    EV_REQ_END   = 3,
    EV_QUERY     = 4,
};

struct ev_hdr {
    unsigned int type;
    unsigned int pid;
    unsigned long long ts; /* bpf_ktime_get_ns (CLOCK_MONOTONIC) */
};

struct ev_sample {
    struct ev_hdr hdr;
    unsigned int nframes;
    unsigned int _pad;
    unsigned long long frames[MAX_FRAMES]; /* zend_function* per frame, leaf first */
};

struct ev_req {
    struct ev_hdr hdr;            /* EV_REQ_START carries method/uri; EV_REQ_END only ts */
    char method[MAX_METHOD];
    char uri[MAX_URI];
};

struct ev_query {
    struct ev_hdr hdr;            /* ts = query start */
    unsigned long long dur_ns;
    unsigned int nframes;         /* PHP call stack at query time (leaf first) */
    unsigned int _pad;
    unsigned long long frames[MAX_FRAMES];
    char query[MAX_QUERY];
};

#endif
