upstream fridab_cli {
    server fridaB-php:8001;
    server fridaB-php:8002;
    server fridaB-php:8003;
    server fridaB-php:8004;
}

server {
    listen 80;

    location / {
        proxy_pass http://fridab_cli;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }
}
