resolver 127.0.0.11 valid=10s;
split_clients "${request_id}" $pool {
    *       "php-dtrace:9000";
}
server {
    listen 80;
    root /var/www/html;
    index index.php;
    location / {
        fastcgi_pass $pool;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
        fastcgi_param REQUEST_URI $request_uri;
        fastcgi_param SCRIPT_NAME /index.php;
    }
}
